# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
    -   id: ruff-check
        args: ["--fix"]
        exclude: netconan/default_reserved_words.py
    -   id: ruff-format
        exclude: netconan/default_reserved_words.py
