githubRepoOwner: intentionet
githubRepoName: netconan
githubHost: github.com
githubRemote: origin
githubBranch: master
requireChecks: true
requireApproval: false
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
